[package]
name = "z3"
version = "0.12.1"
authors = ["Graydon Hoare <graydon@pobox.com>", "Bruce Mitchener <bruce.mitchener@gmail.com>", "Nick Fitzgerald <fitzgen@gmail.com>"]

description = "High-level rust bindings for the Z3 SMT solver from Microsoft Research"
license = "MIT"
keywords = ["FFI", "SMT", "satisfiability", "solver"]
categories = ["api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/z3/"
homepage = "https://github.com/prove-rs/z3.rs"
repository = "https://github.com/prove-rs/z3.rs.git"


[features]
default = []
arbitrary-size-numeral = ["num"]

# If you set neither features below,
# we hope there is a z3 installed as a system library.

# Enable this feature to build bundled Z3 in z3-sys.
bundled-z3 = ["z3-sys/bundled-z3"]

# Enable this feature to use z3 that is built with vcpkg.
# Note that by default vcpkg-rs uses *-windows-static-md triplet on Windows.
vcpkg = ["z3-sys/vcpkg"]

[dependencies]
log = "0.4"

# optional dependencies
num = { version = "0.4.0", optional=true }

[dev-dependencies]
env_logger = "0.10"
semver = "1"

[dependencies.z3-sys]
path = "../z3-sys"
version = "0.8"
