name: Upload prebuilt Z3
on:
  push:
    branches: [ upload-prebuilt-static-z3 ]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_REVISION: 5c82f7e6372c9b0ea25e1fd829dd50235ef37629
      Z3_VERSION: 0.12.2
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.Z3_VERSION }}
          release_name: ${{ env.Z3_VERSION }}
          draft: false
          prerelease: false
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: vcpkg build z3
        uses: johnwason/vcpkg-action@v5
        with:
          pkgs: z3
          triplet: x64-linux
          disable-cache: true
          revision: ${{ env.VCPKG_REVISION }}
          token: ${{ github.token }}
          extra-args: --clean-buildtrees-after-build
      - name: vcpkg build z3
        uses: johnwason/vcpkg-action@v5
        with:
          pkgs: z3
          triplet: x64-osx
          disable-cache: true
          revision: ${{ env.VCPKG_REVISION }}
          token: ${{ github.token }}
          extra-args: --clean-buildtrees-after-build
      - name: vcpkg build z3
        uses: johnwason/vcpkg-action@v5
        with:
          pkgs: z3
          triplet: x64-windows-static-md
          disable-cache: true
          revision: ${{ env.VCPKG_REVISION }}
          token: ${{ github.token }}
          extra-args: --clean-buildtrees-after-build
      - name: prepare artifact
        run: |
          sh z3-sys/scripts/make_artifact.sh ${{ github.workspace }} ${{ env.VCPKG_ROOT }} x64-linux libz3.a
          sh z3-sys/scripts/make_artifact.sh ${{ github.workspace }} ${{ env.VCPKG_ROOT }} x64-osx libz3.a
          sh z3-sys/scripts/make_artifact.sh ${{ github.workspace }} ${{ env.VCPKG_ROOT }} x64-windows-static-md libz3.lib
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/x64-linux.tar.gz
          asset_name: x64-linux.tar.gz
          asset_content_type: application/gzip
        
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/x64-linux.tar.gz
          asset_name: x64-linux.tar.gz
          asset_content_type: application/gzip
        
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/x64-linux.tar.gz
          asset_name: x64-linux.tar.gz
          asset_content_type: application/gzip
        