# Release pipeline (must be triggered manually)
# * Builds for all platforms (with code signing)
# * Uploads build products to stores (GitHub)
name: Prebuild

on: push

jobs:
  windows:
    runs-on: windows-2019
    env:
      BUILD_TYPE: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cd z3-sys/z3
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DZ3_BUILD_LIBZ3_SHARED=OFF -DZ3_BUILD_EXECUTABLE=OFF -DZ3_BUILD_TEST_EXECUTABLES=OFF -DZ3_BUILD_LIBZ3_MSVC_STATIC=ON
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
          tree
  macos:
    runs-on: macOS-10.14
    env:
      BUILD_TYPE: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cd z3-sys/z3
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DZ3_BUILD_LIBZ3_SHARED=OFF -DZ3_BUILD_EXECUTABLE=OFF -DZ3_BUILD_TEST_EXECUTABLES=OFF
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
          tree
  linux:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install cross build tools
        run:  apt update && apt install -y ninja-build cmake g++
        env:
          DEBIAN_FRONTEND: noninteractive
  
      - name: Build
        run: |
          cd z3-sys/z3
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DZ3_BUILD_LIBZ3_SHARED=OFF -DZ3_BUILD_EXECUTABLE=OFF -DZ3_BUILD_TEST_EXECUTABLES=OFF
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
          tree